version: '3.9'

services:
  db:
    container_name: db
    image: postgres:15
    ports:
      - '5432:5432'
    env_file:
      - docker/.db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  django:
    container_name: django
    build:
      context: ./
      dockerfile: docker/Dockerfile.back
    env_file:
      - docker/.django.env
      - docker/.db.env
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/code
    depends_on:
      - db

volumes:
  postgres_data: