# Generated by Django 5.0 on 2023-12-14 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='nazwa')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='nazwa')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='BoardColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='nazwa')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='columns', to='projects.board')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='boards', to='projects.project'),
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MAN', 'Manager'), ('DEV', 'Developer'), ('TES', 'Tester')], default='DEV', max_length=3, verbose_name='role')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMemberRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hard_skills', models.PositiveSmallIntegerField(choices=[(1, 'Bad'), (2, 'Insufficient'), (3, 'Satisfactory'), (4, 'Good'), (5, 'Excellent')], verbose_name='hard skills')),
                ('soft_skills', models.PositiveSmallIntegerField(choices=[(1, 'Bad'), (2, 'Insufficient'), (3, 'Satisfactory'), (4, 'Good'), (5, 'Excellent')], verbose_name='soft skills')),
                ('performance', models.PositiveSmallIntegerField(choices=[(1, 'Bad'), (2, 'Insufficient'), (3, 'Satisfactory'), (4, 'Good'), (5, 'Excellent')], verbose_name='performance')),
                ('activity', models.PositiveSmallIntegerField(choices=[(1, 'Bad'), (2, 'Insufficient'), (3, 'Satisfactory'), (4, 'Good'), (5, 'Excellent')], verbose_name='performance')),
                ('project_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='projects.projectmember')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='nazwa')),
                ('description', models.TextField(verbose_name='description')),
                ('priority', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='L', max_length=1, verbose_name='priority')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('is_archived', models.BooleanField(default=False, verbose_name='is archived')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='projects.projectmember')),
                ('board_column', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tasks', to='projects.boardcolumn')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='projects.projectmember')),
            ],
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('project_member', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='projects.projectmember')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='comments',
            field=models.ManyToManyField(related_name='comments', through='projects.TaskComment', to='projects.projectmember'),
        ),
    ]
